// Generated by scripts/optimize-work.py.
import rayleigh from './rayleigh.webp'
import rayleigh_960 from './responsive/rayleigh-960.webp'
import rayleigh_1600 from './responsive/rayleigh-1600.webp'
import mvtrx_site from './mvtrx-site.webp'
import mvtrx_site_960 from './responsive/mvtrx-site-960.webp'
import mvtrx_site_1600 from './responsive/mvtrx-site-1600.webp'
import mvtrx_exchange from './mvtrx-exchange.webp'
import mvtrx_exchange_960 from './responsive/mvtrx-exchange-960.webp'
import mvtrx_exchange_1600 from './responsive/mvtrx-exchange-1600.webp'
import lightningchart from './lightningchart.webp'
import lightningchart_960 from './responsive/lightningchart-960.webp'
import lightningchart_1600 from './responsive/lightningchart-1600.webp'
import dashtera from './dashtera.webp'
import dashtera_960 from './responsive/dashtera-960.webp'
import dashtera_1600 from './responsive/dashtera-1600.webp'
import sorrento from './sorrento.webp'
import sorrento_960 from './responsive/sorrento-960.webp'
import sorrento_1600 from './responsive/sorrento-1600.webp'
import alexis_dindal from './alexis-dindal.webp'
import alexis_dindal_960 from './responsive/alexis-dindal-960.webp'
import alexis_dindal_1600 from './responsive/alexis-dindal-1600.webp'
import xorbix from './xorbix.webp'
import xorbix_960 from './responsive/xorbix-960.webp'
import xorbix_1600 from './responsive/xorbix-1600.webp'

export const workImages = {
  'rayleigh': { src: rayleigh, width: 2537, height: 892, srcSet: `${rayleigh_960} 960w, ${rayleigh_1600} 1600w, ${rayleigh} 2537w` },
  'mvtrx-site': { src: mvtrx_site, width: 2526, height: 1296, srcSet: `${mvtrx_site_960} 960w, ${mvtrx_site_1600} 1600w, ${mvtrx_site} 2526w` },
  'mvtrx-exchange': { src: mvtrx_exchange, width: 2556, height: 1302, srcSet: `${mvtrx_exchange_960} 960w, ${mvtrx_exchange_1600} 1600w, ${mvtrx_exchange} 2556w` },
  'lightningchart': { src: lightningchart, width: 2532, height: 1300, srcSet: `${lightningchart_960} 960w, ${lightningchart_1600} 1600w, ${lightningchart} 2532w` },
  'dashtera': { src: dashtera, width: 2541, height: 1127, srcSet: `${dashtera_960} 960w, ${dashtera_1600} 1600w, ${dashtera} 2541w` },
  'sorrento': { src: sorrento, width: 2540, height: 1121, srcSet: `${sorrento_960} 960w, ${sorrento_1600} 1600w, ${sorrento} 2540w` },
  'alexis-dindal': { src: alexis_dindal, width: 2542, height: 1302, srcSet: `${alexis_dindal_960} 960w, ${alexis_dindal_1600} 1600w, ${alexis_dindal} 2542w` },
  'xorbix': { src: xorbix, width: 2542, height: 1302, srcSet: `${xorbix_960} 960w, ${xorbix_1600} 1600w, ${xorbix} 2542w` },
} as const
