"""Create high-quality WebP screenshots and responsive variants; never edit sources."""
from pathlib import Path
import hashlib
import json
from PIL import Image

root = Path(__file__).resolve().parents[1]
source_dir = root / "reference-assets"
output_dir = root / "src/assets/work"
output_dir.mkdir(parents=True, exist_ok=True)
(output_dir / "responsive").mkdir(exist_ok=True)
files = {
    "rayleigh": "Rayleigh.png", "mvtrx-site": "mvtrx-site.png",
    "mvtrx-exchange": "exchange.png", "lightningchart": "lightningchart.png",
    "dashtera": "dashtera.png", "sorrento": "sorrento-restaurant.png",
    "alexis-dindal": "alexis-dindal.png", "xorbix": "xorbix.png",
}
report = []
imports = []
entries = []
for name, source_name in files.items():
    source = source_dir / source_name
    before = hashlib.sha256(source.read_bytes()).hexdigest()
    with Image.open(source) as original:
        image = original.convert("RGB")
        width, height = image.size
        destination = output_dir / f"{name}.webp"
        # Keep the full ~2.5K source resolution for high-density desktop screens.
        image.save(destination, "WEBP", quality=94, method=6)
        variants = []
        key = name.replace("-", "_")
        imports.append(f"import {key} from './{name}.webp'")
        for target_width in (960, 1600):
            target_height = round(height * target_width / width)
            variant = output_dir / "responsive" / f"{name}-{target_width}.webp"
            image.resize((target_width, target_height), Image.Resampling.LANCZOS).save(variant, "WEBP", quality=94, method=6)
            imports.append(f"import {key}_{target_width} from './responsive/{name}-{target_width}.webp'")
            variants.append({"width": target_width, "height": target_height, "bytes": variant.stat().st_size})
        with Image.open(destination) as encoded:
            assert encoded.size == image.size
        entries.append(f"  '{name}': {{ src: {key}, width: {width}, height: {height}, srcSet: `${{{key}_960}} 960w, ${{{key}_1600}} 1600w, ${{{key}}} {width}w` }},")
    assert hashlib.sha256(source.read_bytes()).hexdigest() == before
    report.append({"source": source_name, "source_sha256": before, "source_bytes": source.stat().st_size,
                   "output": destination.name, "width": width, "height": height,
                   "output_bytes": destination.stat().st_size, "variants": variants})

(output_dir / "images.ts").write_text("// Generated by scripts/optimize-work.py.\n" + "\n".join(imports) + "\n\nexport const workImages = {\n" + "\n".join(entries) + "\n} as const\n", encoding="utf-8")
(output_dir / "optimization.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
print(json.dumps(report, indent=2))
print(f"Originals: {sum(row['source_bytes'] for row in report):,} bytes")
print(f"Full-resolution WebP: {sum(row['output_bytes'] for row in report):,} bytes")
print(f"960px set: {sum(row['variants'][0]['bytes'] for row in report):,} bytes")
